### ISSUE TITLE
RLDi and REDi different effect direction

### ISSUE THREAD

**Issue by rbarbieri86** [Vivianstats/MAAPER#4]
Hi Vivian,

I am working on a monocytes dataset in a clinical framework and I have a technical question:

When the direction of the RLDi and REDi is opposite how would you try to interpret it?

This seems to happen when a single 3'-most exon site is present for a gene while mutiple intronic/internal PASs are present for the same gene.

Would you consider this situation ambiguous?

Thank you very much in advance!

**Comment by Vivianstats** [comment]
Hi Ruggero,

Thanks for posting this question on Github.

The RLDi score compares expression of all intronic/internal PASs (weighted by length) vs. all PASs on the 3'-most exon, while the REDi score compares the intronic/internal PAS with the largest proportion change vs. the PAS with the largest proportion change on the 3' most exon. Therefore, it is possible that the two scores have opposite signs, especially when there are >2 PASs on the same gene, as you have observed.

For example, consider a gene with 3 intronic PASs and 1 PAS on the 3' most exon. Their proportions in cell type A are respectively:
40%, 30%, 20%, 10% (3' most PAS)
and their proportions in cell type B are:
34%, 24%, 28%, 14%
Then, with some constraints on the PAS positions, the RLDi and REDi of this gene can have opposite signs.

I hope this answers your questions.

Best,
Vivian

**Comment by rbarbieri86** [comment]
Hi Vivian,

Yes it does, thank you for your reply.
 
As a follow up question I would ask if there are any plans to report the number of reads per PAS in the PASs table in addition to the relative amount as percentage.

The reason I ask this is to individuate sites that have low coverage, as that may also contribute to ambiguous situations and hard to interpret results.

Thank you in advance :)


Ruggero

**Comment by Vivianstats** [comment]
Hi Ruggero,

Given the current outputs, you can use the number of reads per gene and the PAS percentages to calculate the number of reads per PAS. 

Best,
Vivian

**Comment by rbarbieri86** [comment]
Hi Vivian,

I see, so the number of reads corresponds to the sum of all the PASs represented, got it.
Thank you for the info :)

Best,
Ruggero

**Comment by AidenSb** [comment]
@Vivianstats Hi Vivian, 
hope all is well; just a quick question, Would you please explain whether REDu and RELu values correspond to condtion1 over condition 2 or condition 2 over condition 1?

**Comment by Vivianstats** [comment]
Hi Ruggero,

I assume you have found out about the RED/RLD scores? We use condition 1 as the reference. You can also see the "APA regulation scores" section in our paper.

Best,
Vivian

**Comment by rbarbieri86** [comment]
Hi Vivian,

Last question was from an user called AidenSb, not me. I did find the info about the RED/RLD scores and thank you for the info on the reference condition, though it wasn't me asking :)

Best,
Ruggero

**Comment by Vivianstats** [comment]
Thank you for letting me know! When I clicked on the Github link in the email notification, it somehow took me to this page.

**Comment by rbarbieri86** [comment]
I suspect he might have just deleted his comment, no harm done ^^
