### ISSUE TITLE
running maaper for more than one sample

### ISSUE THREAD

**Issue by AidenSb** [Vivianstats/MAAPER#5]
Hi Vivian,
Thanks for the great tool. When I run Maaper with one sample per condition it works fine but when I input multiple bam files as a vector for each condition I get the error below, would you please help me with this? 
In the last issue, you mentioned that it is preferred to input multiple bam files (per sample) per condition to Maaper rather than one pseudo-bulk. 

Error in density.default(dist_all, from = 0, to = dist_thre, n = dist_thre + : argument 'x' must be numeric
Traceback:
. maaper(reference.gtf, apa_atlas, bam_c1 = ast_fb_ALSFTLD_bams, 
 .     bam_c2 = ast_fb_control_bams, output_dir = ast_map_out, read_len = 76, 
 .     ncores = 16)
2. wrap(pas_by_gene_single, pas_by_gene = pas_annotation, exons_gr, 
 .     bam_c1, bam_c2, density_train_path, dist_thre, num_thre, 
 .     read_len, num_pas_thre, frac_pas_thre, ncores, save_path, 
 .     run, subset, region, verbose, output_dir, paired = paired)
3. lapply(conds, function(con) {
 .     if (con == "c1") {
 .         bam_paths = bam_c1
 .     }
 .     if (con == "c2") {
 .         bam_paths = bam_c2
 .     }
 .     ss = length(bam_paths)
 .     density_con = lapply(1:ss, function(k) {
 .         message(paste("Start training for condition", con, "-", 
 .             "sample", k, "..."))
 .         bam_path = bam_paths[k]
 .         pdist = get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, 
 .             num_thre, dist_thre, ncores)
 .         gc()
 .         return(pdist)
 .     })
 . })
4. FUN(X[[i]], ...)
5. lapply(1:ss, function(k) {
 .     message(paste("Start training for condition", con, "-", "sample", 
 .         k, "..."))
 .     bam_path = bam_paths[k]
 .     pdist = get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, 
 .         num_thre, dist_thre, ncores)
 .     gc()
 .     return(pdist)
 . })
6. FUN(X[[i]], ...)
7. get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, num_thre, 
 .     dist_thre, ncores)
8. density(dist_all, from = 0, to = dist_thre, n = dist_thre + 1)
9. density.default(dist_all, from = 0, to = dist_thre, n = dist_thre + 
 .     1)
10. stop("argument 'x' must be numeric")

**Comment by AidenSb** [comment]
Update:
I do get the same error when making pseudobulks of the samples too. so probably it's not about inputting multiple samples.

**Comment by Vivianstats** [comment]
Can you post the code you used to run maaper?

**Comment by AidenSb** [comment]
Sorry, my bad. the problem was a minor error in the paths to the bam files in my vectors. 
Thanks

**Comment by AidenSb** [comment]
Hi @Vivianstats,
I still get the error for some of my samples. the code is basically the mapper function: 

```
ast_map_out <- paste0(outdir,"/mapper_out")
maaper(reference.gtf, apa_atlas, bam_c1=ast_fb_bams, bam_c2=ast_fb_ctrl.bams, 
      output_dir=ast_map_out, read_len=91, ncores=60)
```

The problem definitely is about a few of samples, when I exclude them the code runs and I get results but when included or even when run individually I get the error! The bam files don't have any issues(checked with samtools) but they are small as I generated by pseudobuliking a small number of single cells (~20), do you have any ideas?

**Comment by Vivianstats** [comment]
Hi AidenSb, do you get the same error messages as shown above? Can you post the full messages printed by maaper?
As you said the data contain ~20 single cells, one possible reason is there aren't enough reads for MAAPER to learn the distance density.

**Comment by AidenSb** [comment]
Hi @Vivianstats 
I'm running Maaper on many samples and it's apparently not about the size of bam files! I still get the error on some bigger files. working on seeing what's the problem, would appreciate your help.
 here is the error:
```

Error in density.default(dist_all, from = 0, to = dist_thre, n = dist_thre + : argument 'x' must be numeric
Traceback:

1. call_mapper("AST-PP", ast_fb_c1_bams, ast_fb_control_bams)
2. maaper(reference.gtf, apa_atlas, bam_c1 = c1, bam_c2 = c2, output_dir = ast_map_out, 
 .     read_len = 91, ncores = 60)   # at line 4-5 of file <text>
3. wrap(pas_by_gene_single, pas_by_gene = pas_annotation, exons_gr, 
 .     bam_c1, bam_c2, density_train_path, dist_thre, num_thre, 
 .     read_len, num_pas_thre, frac_pas_thre, ncores, save_path, 
 .     run, subset, region, verbose, output_dir, paired = paired)
4. lapply(conds, function(con) {
 .     if (con == "c1") {
 .         bam_paths = bam_c1
 .     }
 .     if (con == "c2") {
 .         bam_paths = bam_c2
 .     }
 .     ss = length(bam_paths)
 .     density_con = lapply(1:ss, function(k) {
 .         message(paste("Start training for condition", con, "-", 
 .             "sample", k, "..."))
 .         bam_path = bam_paths[k]
 .         pdist = get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, 
 .             num_thre, dist_thre, ncores)
 .         gc()
 .         return(pdist)
 .     })
 . })
5. FUN(X[[i]], ...)
6. lapply(1:ss, function(k) {
 .     message(paste("Start training for condition", con, "-", "sample", 
 .         k, "..."))
 .     bam_path = bam_paths[k]
 .     pdist = get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, 
 .         num_thre, dist_thre, ncores)
 .     gc()
 .     return(pdist)
 . })
7. FUN(X[[i]], ...)
8. get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, num_thre, 
 .     dist_thre, ncores)
9. density(dist_all, from = 0, to = dist_thre, n = dist_thre + 1)
10. density.default(dist_all, from = 0, to = dist_thre, n = dist_thre + 
  .     1)
11. stop("argument 'x' must be numeric")
```

**Comment by Vivianstats** [comment]
Can you post the full messages printed by maaper, including those before this error message?

**Comment by AidenSb** [comment]
yes, here you can see the problem occurs when it reaches sample 3. 
```
Prepare reference genome ...

Import genomic features from the file as a GRanges object ... 
OK

Prepare the 'metadata' data frame ... 
OK

Make the TxDb object ... 
Warning message in .get_cds_IDX(mcols0$type, mcols0$phase):
“The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.”
OK

Sequence levels in GTF:

 [1] "chr1"  "chr2"  "chr3"  "chr4"  "chr5"  "chr6"  "chr7"  "chr8"  "chr9" 
[10] "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18"
[19] "chr19" "chr20" "chr21" "chr22" "chrX"  "chrY"  "chrM" 
Prepare PAS annotation ...

16707 genes!

Start training for condition c1 - sample 1 ...

215 genes used for training ...

0.211 fragments longer than 600 ...

Start training for condition c1 - sample 2 ...

235 genes used for training ...

0.1951 fragments longer than 600 ...

Start training for condition c1 - sample 3 ...

0 genes used for training ...

NaN fragments longer than 600 ...

Error in density.default(dist_all, from = 0, to = dist_thre, n = dist_thre + : argument 'x' must be numeric
Traceback:

1. call_mapper("AST-PP", ast_fb_c1_bams, ast_fb_control_bams)
2. maaper(reference.gtf, apa_atlas, bam_c1 = c1, bam_c2 = c2, output_dir = ast_map_out, 
 .     read_len = 91, ncores = 60)   # at line 4-5 of file <text>
3. wrap(pas_by_gene_single, pas_by_gene = pas_annotation, exons_gr, 
 .     bam_c1, bam_c2, density_train_path, dist_thre, num_thre, 
 .     read_len, num_pas_thre, frac_pas_thre, ncores, save_path, 
 .     run, subset, region, verbose, output_dir, paired = paired)
4. lapply(conds, function(con) {
 .     if (con == "c1") {
 .         bam_paths = bam_c1
 .     }
 .     if (con == "c2") {
 .         bam_paths = bam_c2
 .     }
 .     ss = length(bam_paths)
 .     density_con = lapply(1:ss, function(k) {
 .         message(paste("Start training for condition", con, "-", 
 .             "sample", k, "..."))
 .         bam_path = bam_paths[k]
 .         pdist = get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, 
 .             num_thre, dist_thre, ncores)
 .         gc()
 .         return(pdist)
 .     })
 . })
5. FUN(X[[i]], ...)
6. lapply(1:ss, function(k) {
 .     message(paste("Start training for condition", con, "-", "sample", 
 .         k, "..."))
 .     bam_path = bam_paths[k]
 .     pdist = get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, 
 .         num_thre, dist_thre, ncores)
 .     gc()
 .     return(pdist)
 . })
7. FUN(X[[i]], ...)
8. get_pdist_singlePAS(bam_path, exons_gr, pas_by_gene_single, num_thre, 
 .     dist_thre, ncores)
9. density(dist_all, from = 0, to = dist_thre, n = dist_thre + 1)
10. density.default(dist_all, from = 0, to = dist_thre, n = dist_thre + 
  .     1)
11. stop("argument 'x' must be numeric")
```

**Comment by Vivianstats** [comment]
Yes, it shows "0 genes used for training ...". This means that in sample 3, none of the genes with one annotated PAS have enough reads to train the model. To use maaper, you will need to skip this sample or merge it with another sample.

**Comment by AidenSb** [comment]
yes Thanks.
